//TYPES PARA BUSCAR OS CARDS NA API
export const FLASHCARDS_REQUEST = "@flashcards/FLASHCARDS_REQUEST";
export const FLASHCARDS_SUCCESS = "@flashcards/FLASHCARDS_SUCCESS";
export const FLASHCARDS_FAILURE = "@flashcards/FLASHCARDS_FAILURE";
